name: CI

on:
  push:
  pull_request:

jobs:
  judge-you-silently:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies (aka unleash the bloat)
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
      - name: Run tests (brace yourself)
        run: |
          . .venv/bin/activate
          pytest -q
